In [1]:
import pandas as pd
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [2]:
df.drop(['PassengerId','Name','SibSp','Ticket','Cabin','Embarked'],axis = 'columns',inplace = True)

In [4]:
df.drop(['Parch'],axis = 1, inplace = True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [6]:
target = df['Survived']
inputs = df.drop('Survived',axis = 1)

In [10]:
dummies = pd.get_dummies(inputs['Sex']).astype('int64')
dummies.head()

   female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [11]:
inputs = pd.concat([inputs,dummies],axis = 1)
inputs.head()

   Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [12]:
inputs.drop('Sex',axis = 1, inplace = True)
inputs

     Pclass   Age     Fare  female  male
0         3  22.0   7.2500       0     1
1         1  38.0  71.2833       1     0
2         3  26.0   7.9250       1     0
3         1  35.0  53.1000       1     0
4         3  35.0   8.0500       0     1
..      ...   ...      ...     ...   ...
886       2  27.0  13.0000       0     1
887       1  19.0  30.0000       1     0
888       3   NaN  23.4500       1     0
889       1  26.0  30.0000       0     1
890       3  32.0   7.7500       0     1

[891 rows x 5 columns]

In [15]:
inputs.columns[inputs.isna().any()]

Index([], dtype='object')

In [14]:
inputs['Age'] = inputs['Age'].fillna(inputs['Age'].mean())

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(inputs,target,test_size=0.2)

In [38]:
len(X_train)

712

In [39]:
len(X_test)

179

In [40]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [41]:
model.fit(X_train,y_train)

GaussianNB()

In [42]:
model.score(X_test,y_test)

0.7821229050279329

In [43]:
X_test[:10]

     Pclass        Age     Fare  female  male
771       3  48.000000   7.8542       0     1
293       3  24.000000   8.8500       1     0
666       2  25.000000  13.0000       0     1
724       1  27.000000  53.1000       0     1
220       3  16.000000   8.0500       0     1
340       2   2.000000  26.0000       0     1
876       3  20.000000   9.8458       0     1
789       1  46.000000  79.2000       0     1
598       3  29.699118   7.2250       0     1
545       1  64.000000  26.0000       0     1

In [44]:
y_test[:10]

771    0
293    0
666    0
724    1
220    1
340    1
876    0
789    0
598    0
545    0
Name: Survived, dtype: int64

In [45]:
model.predict(X_test[:10])

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
model.predict_proba(X_test[:10])

array([[0.99092045, 0.00907955],
       [0.06270912, 0.93729088],
       [0.98015868, 0.01984132],
       [0.87010383, 0.12989617],
       [0.98890522, 0.01109478],
       [0.95171409, 0.04828591],
       [0.99023305, 0.00976695],
       [0.68511651, 0.31488349],
       [0.99171497, 0.00828503],
       [0.86325466, 0.13674534]])